### ISSUE TITLE
Error adding pycrypto mac

### ISSUE THREAD

**Issue by BoDonkey** [carlalexander/debops-wordpress#160]
Hi,
I'm trying to get debops working on a mac 10.11.6, python 2.7.10. On the installation step of ansible, etc.. I get 

```src/_fastmath.c:36:11: fatal error: 'gmp.h' file not found
    # include <gmp.h>
              ^
    1 error generated.
    error: command '/usr/bin/clang' failed with exit status 1

    ----------------------------------------
Command "/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-lb1Ey3/pycrypto/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-RETHu1-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-build-lb1Ey3/pycrypto/
```

installed gmp with homebrew and then attempted again, but still no luck. Nothing I can find by Google seems to apply. Any thoughts?

**Comment by BoDonkey** [comment]
Okay, I got one step further before failure! In order to get the installation to work, I had to alter the settings of clang.
```
sudo su -
export CFLAGS=-Qunused-arguments
export CPPFLAGS=-Qunused-arguments 
pip install ansible
exit
```
when I bootstraped I got an unreachable error even though I can ping both the ip and the A name. not sure if it is related or not
